name: zero_waste
description: "A Mobile Based Garbage Collection System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 3.3.0
  firebase_auth: 5.1.4
  cloud_firestore: 5.2.1
  provider: ^6.1.0
  go_router: ^14.2.3
  flutter_osm_plugin: ^1.2.0
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  pdf: ^3.11.1
  printing: ^5.13.1
  intl: ^0.19.0
  persistent_bottom_nav_bar: any
  material_dialogs: ^1.1.5
  path_provider: ^2.0.0
  firebase_storage: ^12.1.3
  image_picker: any
  http: any
  flutter_holo_date_picker: ^1.1.3
  flutter_native_splash: any
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/logo.png
    - assets/bgImg.jpg
    - assets/garbage.jpg
  uses-material-design: true

  fonts:
    - family: CustomBins
      fonts:
        - asset: fonts/CustomBins.ttf

flutter_native_splash:
  color: "#0097A7"
  image: assets/Logo.png
  color_dark: "#121212"
  image_dark: assets/Logo.png

  android_12:
    image: assets/Logo.png
    icon_background_color: "#0097A7"
    image_dark: assets/Logo.png
    icon_background_color_dark: "#121212"

  web: false