name: zero_waste
description: "A Mobile Based Garbage Collection System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  firebase_database: any
  qr_flutter: ^4.1.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.0
  go_router: ^14.2.3
  flutter_osm_plugin: ^1.3.0
  cupertino_icons: ^1.0.6
  datepicker_dropdown: ^0.1.4
  dropdown_button2: ^2.3.9
  calendar_date_picker2: ^1.1.6
  pdf: ^3.11.1
  printing: ^5.13.1
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  image: ^4.2.0
  path_provider: ^2.1.4
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  awesome_notifications: ^0.9.3+1
  url_launcher: ^6.3.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/logo.png
    - assets/bgImg.jpg
    - assets/garbage.jpg
  uses-material-design: true

  fonts:
    - family: CustomBins
      fonts:
        - asset: fonts/CustomBins.ttf