name: zero_waste
description: "A Mobile Based Garbage Collection System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 3.3.0
  firebase_auth: 5.1.4
  cloud_firestore: 5.2.1
  provider: ^6.1.0
  go_router: ^14.2.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/Logo.png
    - assets/bgImg.jpg
    - assets/bgImg2.jpg
  uses-material-design: true